### ISSUE TITLE
Feature Request: Text Layout

### ISSUE THREAD

**Issue by vKnmnn** [TeraTech/MMM-WiFiPassword#1]
Hi, thank you for creating this module. I'd like to make the folowing feature requests:

- make display of text optional
- optionally display the text next to the qr code, not below it

**Comment by ekauwe** [comment]
I agree with vKnmnn.  Thanks for creating! In my local copy I enabled toggles for displaying show/hide all text and show/hide creds which I think would be great additions to the current code.

**Comment by TeraTech** [comment]
I'm glad this little project came in handy.  I appreciate these ideas.  You can now show or hide all text.  See documentation for field names.

**Comment by TeraTech** [comment]
You can now display in either vertical or horizontal mode.

**Comment by TeraTech** [comment]
Closed
