### ISSUE TITLE
Display more than one QR Code/Network Information

### ISSUE THREAD

**Issue by ivobrowny** [TeraTech/MMM-WiFiPassword#11]
**Is your feature request related to a problem? Please describe.**
I have more than one WiFi network, i.e. a 5GHz and a 2.4GHz band.

**Describe the solution you'd like**
Hence, I would love to be able to display both QR Codes at the same time, either stacked or next to each other.

Could this be implemented?

**Comment by TeraTech** [comment]
Is there a problem with using this module twice in your main config file like this:

`modules:[
  {
    module: 'MMM-WiFiPassword',
    position: "top_left",
      config: {
        //See 'Configuration options' for more information.
        network: "my_network", 
        password: "my_pass",
      }
  },
  {
    module: 'MMM-WiFiPassword',
    position: "top_left",
      config: {
        //See 'Configuration options' for more information.
        network: "my_network2", 
        password: "my_pass2",
      }
  },
]`

**Comment by TeraTech** [comment]
Assuming that suggestion to use 2 modules was enough. Closed
