### ISSUE TITLE
White Line above QR-Code

### ISSUE THREAD

**Issue by yuzedo** [TeraTech/MMM-WiFiPassword#12]
**Describe the bug**
In the github preview image there is no white line above the QR-Code
Integrating the module adds a white line which I want to remove. 

**To Reproduce**
1. Install MMM-WifiPassword
2. Launch MM
3. See error

**Expected behavior**
There should not be a white line - as seen in the preview image.

**Screenshots**

**Comment by yuzedo** [comment]
Here is my config:	 

	 qrSize: 150,
	  colorDark: "#000",
	  colorLight: "#fff",
	  authType: "WPA", 
	  header: "", 
	  network: "censored",
	  password: "censored",
	  hiddenId: false,
	  layoutVertical: true,  
	  showNetwork: true, 
	  showPassword: true, 
	  showAuthType: false,
	  debug: false
```

**Comment by yuzedo** [comment]
Found out it has to do something with the CSS but I can't seem to find which entry I have to edit.
Is there a way to change the font as well?

**Comment by CFenner** [comment]
@yuzedo this is due to the empty header line in your config. I added #19 to fix this. Also the header should not be rendered by the module from my point of view but by the module framework.

BTW: Your WIFI settings can be decoded from the QR code you provided.
