### ISSUE TITLE
Support for PEAP

### ISSUE THREAD

**Issue by Sqrooge** [TeraTech/MMM-WiFiPassword#21]
Is it possible that this will get support for enterprise (PEAP) networks?
these require user login.
would help me out big time

thanks in advance

**Comment by TeraTech** [comment]
Hi @Sqrooge, sorry it took so long for me to respond. I made this app a few years ago and never expected to have so many others interested in it! I barely have time to work on this anymore, but there are others who have forked this code and are making improvements to it all the time. If you found a solution somewhere, feel free to post it here.
