### ISSUE TITLE
"Could not find main module js file" error message

### ISSUE THREAD

**Issue by greaser9** [TeraTech/MMM-WiFiPassword#22]
All software is installed properly and the config.js is correct as well. Double/triple checked everything yet when I launch the MM nothing shows up. Any idea what could be wrong? 

Within the terminal it says "Error! Could not find main module js file" for MMM-WifiPassword. I don't know why it doesn't seem to be able to locate it, because everything is there when I go into the file itself. Any ideas on how to fix this would be appreciated.

**Comment by greaser9** [comment]
Fixed!

did not capitalize the F in WiFi when installing it initially. Hopefully someone else sees this if they make the same mistake as me so they don't spend hours scanning everything else.

**Comment by TeraTech** [comment]
Hi @greaser9, sorry it took so long for me to respond.  I made this app a few years ago and never expected to have so many others interested in it!  I barely have time to work on this anymore, but there are others who have forked this code and are making improvements to it all the time.  I'm glad you got it to work!
