### ISSUE TITLE
update of MMM-WiFiPassword

### ISSUE THREAD

**Issue by RIKKO14** [TeraTech/MMM-WiFiPassword#4]
Hello,
this day on my MM 3 update was displayed, MMM-GoogleAssistant, MMM-Assistant2Display and MMM-WiFiPassword, after performing the updates of MMM-GoogleAssistant, MMM-Assistant2Display, I was not asked to update update of MMM-WiFiPassword, is this normal? How else to update MMM-WiFiPassword?

**Comment by Tyler-sudo** [comment]
Head into the folder of the module vi terminal and type: git pull, then npm install.

This would update it to the latest version.

**Comment by RIKKO14** [comment]
ok, thanks you
