### ISSUE TITLE
showAuthType, showPassword, showNetwork = False, not respected?

### ISSUE THREAD

**Issue by OliPassey** [TeraTech/MMM-WiFiPassword#9]
**Describe the bug**
I am using the showAuthType, showPassword, showNetwork: "false" flags, but they are showing regardless.

**To Reproduce**
```
		{
			module: 'MMM-WiFiPassword',
			position: "bottom_right",
			  config: {
				//See 'Configuration options' for more information.
				showAuthType: "false",
				showPassword: "false",
				showNetwork: "false",
				network: "**REMOVED**", 
				password: "**REMOVED**",
				header: "Scan for WiFi",
				qrSize: "250",
			  }
		  },
```

**Expected behavior**
Display Heading, QR Code and nothing else.

**Desktop (please complete the following information):**
Latest Raspbian
Chrome on Windows 10, but also local on the rPi - Chromium / Magic Mirror local display
Latest

Is this a bug or have i misconfigured something that you can see?

**Comment by jimus888** [comment]
Hi,

Try removing the " " from the false.

e.g
showAuthType: false,

**Comment by TeraTech** [comment]
I
